server:
  port: 8766
spring:
  application:
    name: wolf-cloud-zuul
eureka:
  client:
    servicerl:
     default-zone: http://localhost:8761/eureka/
zuul:
  routes:
    feign:
      path: /feign/**
      url: http://localhost:8765/
    ribbon:
      path: /ribbon/**
      serviceId: wolf-cloud-ribbon-8764
    wolf-cloud-user: /user/**