server:
  port: 8767
spring:
  application:
    name: wolf-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BinWolf/wolf-cloud-parent.git
          search-paths: wolf-cloud-parent/wolf*

eureka:
  client:
    servicerl:
     default-zone: http://localhost:8761/eureka/